import './assets/sass/main.scss';
import './js/main.js';
import './contact-form.php';
import './survey.php';
import './subscribe.php';
require(`animate.css`);
require(`./index.html`);
require(`./contact.html`);
require(`./impressum.html`);
require(`./datenschutz.html`);
require(`./cookie-richtlinien.html`);
